### ISSUE TITLE
make it harder to get component.json "scripts" field *wrong*

### ISSUE THREAD

**Issue by jasonkuhrt** [componentjs/component#565]
I think these should work identically but currently the former will break at `component build` time:

```
  "scripts": [
    "./index.js",
    "./lib/**/*.js"
  ],
```

```
  "scripts": [
    "index.js",
    "lib/**/*.js"
  ],
```

**Comment by timaschew** [comment]
the reason is that the `register` function is written in this style:

```
require.register("app/foo/./index.js", ...
```

I added a note to the component.json spec: https://github.com/componentjs/spec/blob/master/component.json/specifications.md#file-paths
