### ISSUE TITLE
Private Repo doesn't seem to be working

### ISSUE THREAD

**Issue by aprilb** [componentjs/component#628]
I have a private repo with the correct user permissions --problem is that it won't load.

```
% DEBUG=remotes* component install treetopllc/shared-scripts@master

  remotes:local checking local components at /home/nobleweb/go/src/github.com/treetopllc/nobleweb/components +0ms
  remotes:local resolving local remote +10ms
  remotes:local checking folder: /home/nobleweb/go/src/github.com/treetopllc/nobleweb/components/treetopllc/shared-scripts +0ms
  remotes:github GET "https://api.github.com/repos/treetopllc/shared-scripts/tags" +4ms
  remotes:github GET "https://raw.githubusercontent.com/treetopllc/shared-scripts/master/component.json" +592ms
  remotes:github GET "https://raw.githubusercontent.com/treetopllc/shared-scripts/master/component.json" +307ms
  remotes:bitbucket GET "https://api.bitbucket.org/1.0/repositories/treetopllc/shared-scripts/tags" +245ms
  remotes:bitbucket GET "https://api.bitbucket.org/1.0/repositories/treetopllc/shared-scripts/raw/master/component.json" +437ms
  remotes:bitbucket GET "https://bitbucket.org/api/1.0/repositories/treetopllc/shared-scripts/raw/master/component.json" +391ms
  remotes:bitbucket GET "https://api.bitbucket.org/1.0/repositories/treetopllc/shared-scripts/raw/master/component.json" +385ms
  remotes:bitbucket GET "https://bitbucket.org/api/1.0/repositories/treetopllc/shared-scripts/raw/master/component.json" +381ms

       fatal : no remote found for dependency "treetopllc/shared-scripts@master". Visit http://component.github.io/troubleshooting for help.

  remotes:github:api used 1 +440ms
```

**Comment by timaschew** [comment]
is it on github or bitbucket?

**Comment by aprilb** [comment]
github

**Comment by timaschew** [comment]
need more information: 
- content of your component.json
- which auth mechanism are you using?
- which version of component?

**Comment by aprilb** [comment]
{
  "name": "shared-scripts",
  "repository": "treetopllc/shared-scripts",
  "version": "0.0.0",
  "private": true,
  "description": "Treetop Commons shared Javascript files",
  "main": "index.js",
  "scripts": [
    "index.js"
  ]
}

**Comment by aprilb** [comment]
netrc which is valid. component version 1.0.0

**Comment by timaschew** [comment]
I add add you to my private test reop, it works fine for me with component 1.0.2

```
$ component install timaschew/TodoFPM-test-private

   installed : timaschew/todofpm-test-private@master in 783ms
     install : complete 
```

**Comment by timaschew** [comment]
can you show me the content of your netrc (without the password/token)

**Comment by aprilb** [comment]
machine github.com
  login xxxxxx
  password x-oauth-basic

machine api.github.com
  login xxxxxx
  password x-oauth-basic

**Comment by aprilb** [comment]
actually i am using component 1.0.2

**Comment by aprilb** [comment]
did you say you added me to timaschew/TodoFPM-test-private?

component install timaschew/TodoFPM-test-private


       fatal : no remote found for dependency "timaschew/todofpm-test-private@master". Visit http://component.github.io/troubleshooting for help.

**Comment by timaschew** [comment]
your netrc is wrong, you need to change the first host entry, instead of `github.com` you need `raw.githubusercontent.com`

There was an error in the guide, it was fixed some weeks ago: https://github.com/componentjs/guide/blob/master/component/getting-started.md#configuring-github-access

**Comment by aprilb** [comment]
ok, great. yeah, that did it.  thanks for looking into it.

**Comment by aprilb** [comment]
actually, looks like I needed all three:

$ cat $HOME/.netrc
machine github.com
  login xxxxxxxxx
  password x-oauth-basic
 
machine raw.githubusercontent.com
  login xxxxxxxxx
  password x-oauth-basic
 
machine api.github.com
  login xxxxxxxxx
  password x-oauth-basic

**Comment by timaschew** [comment]
What's the error if you omit the github.com host? Because there should be no request for this host.
If there is an error `DEBUG=* component install user/repo` should show where the error comes from

**Comment by aprilb** [comment]
Here is the error if i leave out api.github.com:

Error: no remote found for dependency "mochajs/mocha".
    at Resolver.<anonymous> (/home/nobleweb/go/src/github.com/treetopllc/nobleweb/node_modules/component-resolver/build/semver.js:565:13)
    at Generator.invoke (/home/nobleweb/go/src/github.com/treetopllc/nobleweb/node_modules/component-resolver/build/index.js:141:31)
    at Generator.invoke (/home/nobleweb/go/src/github.com/treetopllc/nobleweb/node_modules/component-resolver/build/index.js:79:50)
    at next (/home/nobleweb/go/src/github.com/treetopllc/nobleweb/node_modules/component-resolver/node_modules/co/index.js:74:21)
    at /home/nobleweb/go/src/github.com/treetopllc/nobleweb/node_modules/component-resolver/node_modules/co/index.js:93:18
    at Gunzip.onEnd (/home/nobleweb/go/src/github.com/treetopllc/nobleweb/node_modules/component-remotes/node_modules/cogent/node_modules/raw-body/index.js:136:7)
    at Gunzip.g (events.js:180:16)
    at Gunzip.emit (events.js:117:20)
    at _stream_readable.js:943:16
    at process._tickCallback (node.js:419:13)

**Comment by timaschew** [comment]
no, drop `github.com` __not__ `api.github.com`

> instead of github.com you need raw.githubusercontent.com

**Comment by aprilb** [comment]
kk.  Will do.
