### ISSUE TITLE
Getting Uncaught Error: failed to require template

### ISSUE THREAD

**Issue by aprilb** [componentjs/component#629]
Getting this error in the debugging console when attempting to require a template.

My component.json with:

```
  "templates": [
    "template.hbs"
  ]
```

the index.js where it is being required:

Tried this
```
MyScript.prototype.template = require("./template");
```

```
MyScript.prototype.template = require("./template.hbs");
```

Both result in an error.

**Comment by sankargorthi** [comment]
I ran into this too - I was running a `--standalone` build. Is that how you're using component too? @aprilb

**Comment by timaschew** [comment]
- what is the error?
- how your build output looks?
- how you build your app?
- do you use the hbs plugin and if yes, how?

**Comment by aprilb** [comment]
Good question.  Yeah, I have just begun moving some local scripts into a private repository --not realizing things would break.  I just assumed it would continue to work as it has.

The error is:
```
Uncaught Error: failed to require "./template.hbs"
```

Locally using handlebars plugin:
```
var handlebars = require("component-build-handlebars");
```

Can you clarify what you mean by build output?

Building the app as follows:
```
node build/builder.js
```

The contents of that file:
https://gist.github.com/aprilb/aedad66feec4236f1982

**Comment by aprilb** [comment]
Error:
```
Uncaught Error: failed to require "./template.hbs"
```

**Comment by aprilb** [comment]
@sankargorthi using component-build-handlebars plugin

**Comment by sankargorthi** [comment]
@aprilb are you using a custom builder? How's the plugin parsing your templates?

**Comment by aprilb** [comment]
Here is the build file:
https://gist.github.com/aprilb/aedad66feec4236f1982

Versions:
"component": "~1.0.0",
"component-build-handlebars": "0.0.1",

**Comment by aprilb** [comment]
@sankargorthi here is the builder:
https://github.com/dominicbarnes/component-build-handlebars

**Comment by sankargorthi** [comment]
Everything looks good to me so far. And you aren't using the standalone builder either - so no idea why your template's not loading.

**Comment by timaschew** [comment]
why you use also the `string` plugin? 
https://gist.github.com/aprilb/aedad66feec4236f1982#file-gistfile1-txt-L58

the readme of the handlebars plugin don't mention the `string` plugin, so it looks like you using it wrong.

**Comment by aprilb** [comment]
Removing the string plugin doesn't seem to have an affect  --still getting the same error.  But the person who wrote the handlebars plugin I mentioned --also wrote this part of the script.  It doesn't fail if these scripts are local --they are only failing now that they are being required as a remote dependency.

**Comment by timaschew** [comment]
If you want help, please provide a repository where I can reproduce the problem.
