### ISSUE TITLE
On chrome debug points off by two lines for --dev builds 

### ISSUE THREAD

**Issue by sankargorthi** [componentjs/component#631]
putting debug points on the sources of [home.html](https://github.com/componentjs/bundler-example) shows the incorrect line of code. (happens on canary as well)

![screen shot 2015-03-14 at 4 13 07 pm](https://cloud.githubusercontent.com/assets/924700/6653991/1cbf7c00-ca65-11e4-988a-dae2558ed01a.png)

![screen shot 2015-03-14 at 4 13 22 pm](https://cloud.githubusercontent.com/assets/924700/6653993/2086b92a-ca65-11e4-955d-78df39356c59.png)

![screen shot 2015-03-14 at 4 13 28 pm](https://cloud.githubusercontent.com/assets/924700/6653994/245b3742-ca65-11e4-8cf2-1ebda854c978.png)

Works in Firefox as the debugger doesn't show the

    (function(exports, module
    /**/) {

lines in the source.

**Comment by KenanSulayman** [comment]
That's a Chrome bug. We ran into it as soon as Canary became Stable. I am confident that the comments used for annotations are causing this bug in Chrome and it wasn't properly unit tested. (*regression*, that is)

**Comment by sankargorthi** [comment]
https://code.google.com/p/chromium/issues/detail?id=451015

Removing new lines in the require implementation didn't seem to help either. Closing this as it's not component(1)'s problem.
