### ISSUE TITLE
Getting Failed to Require message

### ISSUE THREAD

**Issue by aprilb** [componentjs/component#632]

**Comment by timaschew** [comment]
to less information: no install log, no build output file via gist for intance

**Comment by aprilb** [comment]
I am not sure what the question is?

**Comment by timaschew** [comment]
I'm not sure what your issue is ;)

**Comment by aprilb** [comment]
sorry, I just don't know how to debug this or what to even post for the issue.  All I know is that the module is not being required yet I get absolutely no build errors of any kind.  All I see is a console error.

For the purposes of testing I made the two repos public:
https://github.com/treetopllc/explore-search
https://github.com/treetopllc/explore-filter-entity

**Comment by timaschew** [comment]
can you explain why you delete deleted the description and closed the issue?
