### ISSUE TITLE
Clean up the maintainers list?

### ISSUE THREAD

**Issue by ChALkeR** [componentjs/component#642]
Atm, there are [31 accounts](https://www.npmjs.com/package/component/access) with publish access to npm package [Component](https://www.npmjs.com/package/component). That looks a bit excessive to me, and that is one of the reasons why there were at least two accounts with [leaked credentials](https://github.com/ChALkeR/notes/blob/master/Do-not-underestimate-credentials-leaks.md) on that list.

Perhaps you could remove some accounts from that list, especially now, when the project is not maintained anymore and no updates are planned.

**Comment by timaschew** [comment]
Sounds good, thank you. I removed most of the people, 7 have access now.

Did the people get any notification that their credentials were leaked?
Just want to be sure it wasn't me...

**Comment by ChALkeR** [comment]
@timaschew Yes, they did.

Thanks, looks better now!
